var ltmp_en_arr={
	settings_caption:'Vizonator settings',
	current_status:'Current status',
	status_used_account:'used <b>{account}</b> account',
	empty_memo_title:'Private memo key was not provided, anyone can see your memo in awards on blockchain explorer',
	memo_title:'Private memo key was provided, your memo in awards will be encrypted, only social gate can see it',
	empty_active_title:'Private active key was not provided',
	active_title:'Private active key was provided, you can use it with a web3 provider',
	remove_account_caption:'Remove account credentials',
	remove_last_account_caption:'Remove account credentials and all settings',

	select_account_title:'Select account',
	current_account_caption:'Current account',
	delete_account_caption:'Delete account data',
	edit_account_caption:'Edit account data',
	add_account_title:'Adding an account',
	edit_account_title:'Edit account',
	add_account_caption:'Add account',

	empty_account:'account was not provided',
	connect_account:'Connect VIZ account',
	form_login:'Account login',
	form_login_edit_descr:'Selected account (read only)',
	form_regular_key:'Private regular key',
	form_regular_key_short:'Private regular key',
	form_regular_key_edit_descr:'Your can edit private regular key',
	form_memo_key:'Private memo key',
	form_memo_key_short:'Private memo key',
	form_memo_key_descr:'Needed for encrypt memo',
	form_active_key:'Private active key',
	form_active_key_short:'Private active key',
	form_active_key_descr:'Needed for web3 operations (transfers, delegation)',
	form_key_exist:'The key is saved',
	form_save_caption:'Save account credentials',
	form_edit_caption:'Save changes',
	form_optional:'optional',
	form_invalid_keys:'Provided keys are invalid: ',

	removed_data:'✔️ All data was removed from local storage. <a class="refresh-page dashed">Reload the page</a> to restart the setting.',

	language:'language',
	energy_step:'energy step in percent',
	award_energy:'default award energy in percent',
	dark_mode:'Dark mode',
	save_settings_caption:'Save settings',

	lock_caption:'Encrypt with a password',
	lock_descr:'You can add a password to use Visonator. All data will be encrypted.',
	lock_password:'password',
	lock_button:'Encrypt',
	locked_descr:'<b>All data have beed encrypted by password.</b> You can change it or remove encryption.',
	lock_update_button:'Update password',
	lock_remove_button:'Remove encryption',

	history_form_title:'History',
	load_history_action:'Load history&hellip;',
	history_fully_load:'✔️ History is fully loaded',history_adaptive_data:'Date:',
	history_award:'Awarding <a class="view-account" href="https://info.viz.plus/accounts/{receiver}/" target="_blank">{receiver}</a> with <span class="view-percent">{energy}%</span> energy',
	history_award_memo:' with memo ',
	history_fixed_award:'Awarding <a class="view-account" href="https://info.viz.plus/accounts/{receiver}/" target="_blank">{receiver}</a> by amount <span class="view-tokens">{reward_amount}</span>',
	history_delegate_vesting_shares:'<span class="view-tokens">{shares}</span> delegated <a class="view-account" href="https://info.viz.plus/accounts/{delegatee}/" target="_blank">{delegatee}</a>',
	history_income_delegate_vesting_shares:'<span class="view-tokens">{shares}</span> delegated from <a class="view-account" href="https://info.viz.plus/accounts/{delegator}/" target="_blank">{delegator}</a>',
	history_revoke_delegate_vesting_shares:'Revoke delegation <a class="view-account" href="https://info.viz.plus/accounts/{delegatee}/" target="_blank">{delegatee}</a>',
	history_income_revoke_delegate_vesting_shares:'Revoked delegation from <a class="view-account" href="https://info.viz.plus/accounts/{delegator}/" target="_blank">{delegator}</a>',
	history_receive_award:'Award received <span class="view-tokens">{shares}</span> from <a class="view-account" href="https://info.viz.plus/accounts/{initiator}/" target="_blank">{initiator}</a>',
	history_create_invite:'A check for <span class="view-tokens">{tokens}</span> with the verification code <span class="view-key">{key}</span>',
	history_claim_invite_balance:'A check with a code <span class="view-key">{key}</span> is redeemed',
	history_use_invite_balance:'A check with a code <span class="view-key">{key}</span> is redeemed',
	history_transfer_from:'<span class="view-tokens">{tokens}</span> transfered to <a class="view-account" href="https://info.viz.plus/accounts/{to}/" target="_blank">{to}</a>',
	history_transfer_to:'<span class="view-tokens">{tokens}</span> received from <a class="view-account" href="https://info.viz.plus/accounts/{from}/" target="_blank">{from}</a>',
	history_transfer_memo:' with memo ',
	history_transfer_to_vesting_from:'<span class="view-tokens">{tokens}</span> staked to social capital <a class="view-account" href="https://info.viz.plus/accounts/{to}/" target="_blank">{to}</a>',
	history_transfer_to_vesting_to:'<span class="view-tokens">{tokens}</span> received to social capital from <a class="view-account" href="https://info.viz.plus/accounts/{from}/" target="_blank">{from}</a>',
	history_withdraw_vesting_stop:'Stopping the social capital unstake',
	history_withdraw_vesting:'Activation of unstake social capital with an amount of <span class="view-tokens">{shares}</span>',
	history_fill_vesting_withdraw:'Received <span class="view-tokens">{tokens}</span> by social capital unstake',
	history_fill_vesting_withdraw_from:'<a class="view-account" href="https://info.viz.plus/accounts/{to}/" target="_blank">{to}</a> account is sent <span class="view-tokens">{tokens}</span> from social capital unstaking',
	history_fill_vesting_withdraw_to:'Received <span class="view-tokens">{tokens}</span> from social capital unstaking by account <a class="view-account" href="https://info.viz.plus/accounts/{from}/" target="_blank">{from}<a>',

	default_date_utc:' UTC',
	default_no_items:'No entries found.',

	rules_caption:'Rules',
	delete_rule:'delete',
	empty_rules:'No rules were found. You can remember a rule to approve or refuse operations of a certain type for an individual site by checking the "Remember" box.',

	need_encode_state:'Unlock Vizonator first',
	unlock_form:'<input type="password" autocomplete="off" class="decode_password" value="" placeholder="%%lock_password%%"><div class="big-icon"><a class="header-icon unlock-action">{icon}</a></div>',
	configure_account:'Configure VIZ account',
	used_account:'Account',
	advertise_page:'Advertise this page',
	saved:'Saved',
	energy_caption:'Energy',
	capital_caption:'Social Capital',
	balance_caption:'Balance',
	show_effective_capital:'Count the delegation',
	stake_form_title:'Stake Social Capital',
	unstake_form_title:'Unstake Social Capital',
	delegate_form_title:'Delegation',
	wallet_form_title:'Wallet',
	award_form_title:'Award',
	publish_form_title:'Publish',

	stake_action:'Stake',

	stop_unstake_action:'Stop unstaking',
	unstake_duration_caption:'Duration',
	unstake_action:'Start unstaking',
	unstake_withdraw_rate_caption:'Withdraw rate',
	unstake_next_withdraw_caption:'Next withdraw',
	unstake_awaiting_withdraw_caption:'Awaiting unstake',
	default_days:'days',
	default_hours:'hours',

	delegate_form_account:'Recipient',
	delegate_action:'Delegate',
	delegate_hint:'An empty or zero amount will start the delegation cancellation process, which will last one day.',

	publish_action:'Publish',
	publish_form_text:'Text',
	publish_form_share:'Share current tab',
	publish_hint:'Warning! Everything sent to the blockchain cannot be deleted or hidden.',
	publish_success_link:'✔️ <a href="{link}" target="_blank">Open post</a>',

	transfer_form_account:'Recipient',
	transfer_form_memo:'Memo',
	transfer_form_encode_memo:'Encrypt',
	transfer_action:'Send',

	award_form_account:'Recipient',
	award_form_memo:'Memo',
	award_form_encode_memo:'Encrypt',
	award_form_fixed_flag:'Fix amount',
	award_action:'Award',

	default_recipient_error:'Error in recipient',
	recipient_memo_error:'Encrypted memo not supported by recipient',
	encrypt_memo_error:'Encryption error',
	default_not_enough_energy:'Not enough energy',
	default_enter_energy:'Enter the amount of energy',
	default_enter_amount:'Enter the amount',
	default_check_amount:'Check the amount',
	default_insufficient_funds:'Insufficient balance',
	default_insufficient_potential:'Insufficient potencial',
	operation_error:'❌ Operation error',
	operation_success:'✔️ Operation was successful',

	operation_error:'Error, try again.',
	refuse_caption:'Refuse',
	approve_caption:'Approve',
	save_rule_caption:'Remember',

	memo_caption:'Memo',
	encode_memo_caption:'Encode memo',
	sequence_caption:'Sequence',
	beneficiaries_caption:'Beneficiaries',
	origin_caption:'Origin',
	spend_energy_caption:'Spend energy',
	max_energy_caption:'Max spending energy',
	reward_amount_caption:'Reward amount',
	amount_caption:'Amount',
	authority_caption:'Authority type',
	protocol_caption:'Protocol',
	json_caption:'JSON',
	vote_percent_caption:'Vote percent',
	operations_caption:{
		transfer:'Transfer to',
		transfer_to_vesting:'Stake to',
		withdraw_vesting:'Unstake from',
		delegate_vesting_shares:'Delegate to',
		undelegate_vesting_shares:'Undelegate from',
		committee_vote_request:'Committee vote for',
		custom:'Custom by',
		get_custom_account:'Get account info',
		get_custom_current_account:'Get current account info',
		get_account:'Get current account',
		get_settings:'Get settings',
		account_metadata:'Update meta for',
		get_account_history:'Get history for',
		get_current_account_history:'Get account history',
		passwordless_auth:'Passwordless authentification',
	}
};